build:
  version: 2016-03-14 # version of the build schema.
  steps:
    node-service:
      name: dym-node-image
      dockerfile: ./docker/node/Dockerfile
    laravel-service:
      name: dym-laravel-image
      dockerfile: ./docker/laravel/Dockerfile
      depends_on:
        - node-service
    node-production-service:
      name: dym-node-production-image
      dockerfile: ./docker/node/production/Dockerfile
      no_cache: true
      depends_on:
        - laravel-service
    laravel-production-service:
      name: dym-laravel-production-image
      dockerfile: ./docker/laravel/production/Dockerfile
      depends_on:
        - node-production-service