version: 2
services:
  laravel-service:
    git_url: git@bitbucket.org:ottosave/ottosave_app.git
    git_branch: master
    ports:
    - container: 80
      http: 80
      https: 443
    command: "/var/www/docker/laravel/production/start.sh"
    use_habitus: true
    use_habitus_step: laravel-production-service
    health:
      ready:
        type: http
        endpoint: "/"
        protocol: http
        timeout: 300
        initial_delay: 2
  redis-service:
      git_url: git@bitbucket.org:ottosave/ottosave_app.git
      git_branch: master
      ports:
      - '6379'
      dockerfile_path: Dockerfile
      use_habitus: true
      use_habitus_step: redis-service
      habitus_filename: cloud66/redis/build.yml
      habitus_params: ''
